# utils/symbols.py
SYMBOL_TO_COINGECKO_ID = {
    # Top Market Cap
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "BNB": "binancecoin",
    "XRP": "ripple",
    "SOL": "solana",
    "ADA": "cardano",
    "DOGE": "dogecoin",
    "TRX": "tron",
    "AVAX": "avalanche-2",
    "LINK": "chainlink",
    "DOT": "polkadot",
    "MATIC": "polygon-ecosystem-token",
    "POL": "polygon-ecosystem-token",
    "LTC": "litecoin",
    "UNI": "uniswap",
    "ATOM": "cosmos",
    "FIL": "filecoin",
    "APT": "aptos",
    "ARB": "arbitrum",
    "OP": "optimism",
    "NEAR": "near",
    "INJ": "injective-protocol",
    "SUI": "sui",
    "PEPE": "pepe",
    "SHIB": "shiba-inu",
    # Exchange Tokens
    "OKB": "okb",
    "MNT": "mantle",
    "CRO": "crypto-com-chain",
    "KCS": "kucoin-shares",
    "GT": "gate-token",
    "HT": "huobi-token",
    # DeFi
    "AAVE": "aave",
    "MKR": "maker",
    "SNX": "havven",
    "CRV": "curve-dao-token",
    "LDO": "lido-dao",
    "COMP": "compound-governance-token",
    "1INCH": "1inch",
    "BAL": "balancer",
    "SUSHI": "sushi",
    "YFI": "yearn-finance",
    "DYDX": "dydx",
    "GMX": "gmx",
    "GNS": "gains-network",
    "RDNT": "radiant-capital",
    # Layer 1 & Layer 2
    "FTM": "fantom",
    "ALGO": "algorand",
    "EGLD": "elrond-erd-2",
    "HBAR": "hedera-hashgraph",
    "ICP": "internet-computer",
    "VET": "vechain",
    "XLM": "stellar",
    "EOS": "eos",
    "XTZ": "tezos",
    "THETA": "theta-token",
    "KAVA": "kava",
    "ZIL": "zilliqa",
    "ONE": "harmony",
    "CELO": "celo",
    "ROSE": "oasis-network",
    "MINA": "mina-protocol",
    "FLOW": "flow",
    "CFX": "conflux-token",
    "CORE": "coredaoorg",
    "SEI": "sei-network",
    "TIA": "celestia",
    "STRK": "starknet",
    "PYTH": "pyth-network",
    "JUP": "jupiter-exchange-solana",
    "WIF": "dogwifcoin",
    "BONK": "bonk",
    "JTO": "jito-governance-token",
    "TNSR": "tensor",
    "BOME": "book-of-meme",
    # Gaming & Metaverse
    "AXS": "axie-infinity",
    "SAND": "the-sandbox",
    "MANA": "decentraland",
    "ENJ": "enjincoin",
    "GALA": "gala",
    "IMX": "immutable-x",
    "GMT": "stepn",
    "GST": "green-satoshi-token",
    "PIXEL": "pixels",
    "PORTAL": "portal-gaming",
    # AI & Data
    "FET": "fetch-ai",
    "OCEAN": "ocean-protocol",
    "RNDR": "render-token",
    "GRT": "the-graph",
    "NMR": "numeraire",
    "TAO": "bittensor",
    "WLD": "worldcoin-wld",
    "AGIX": "singularitynet",
    # Storage & Infrastructure
    "AR": "arweave",
    "HNT": "helium",
    "ANKR": "ankr",
    "API3": "api3",
    "BAND": "band-protocol",
    # Meme & Others
    "FLOKI": "floki",
    "BABYDOGE": "baby-doge-coin",
    "WEN": "wen-4",
    "MYRO": "myro",
    "POPCAT": "popcat",
    "MEW": "cat-in-a-dogs-world",
    # Gold & Commodity Token
    "PAXG": "pax-gold",
    "XAUT": "tether-gold",
    # Cross-chain & Bridge
    "RUNE": "thorchain",
    "STX": "blockstack",
    "RSR": "reserve-rights-token",
    "REN": "republic-protocol",
    # Privacy
    "XMR": "monero",
    "ZEC": "zcash",
    "SCRT": "secret",
    # Old but still traded
    "BCH": "bitcoin-cash",
    "BSV": "bitcoin-cash-sv",
    "ETC": "ethereum-classic",
    "XEM": "nem",
    "NEO": "neo",
    "WAVES": "waves",
    "ZRX": "0x",
    "BAT": "basic-attention-token",
}


def get_coin_id(pair: str):
    """
    Ambil coin_id dari pair, terlepas dari formatnya
    ("BTC" atau "BTC/USDT" sama-sama bisa diproses).
    Ini SATU-SATUNYA titik lookup coin_id di seluruh codebase.
    """
    symbol = pair.split("/")[0].upper().strip()
    return SYMBOL_TO_COINGECKO_ID.get(symbol)
